spring:
  datasource:
    url: jdbc:postgresql://localhost:2021/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8084
